### ISSUE TITLE
Crash when recording from texture

### ISSUE THREAD

**Issue by bakwc** [RenderHeads/UnityPlugin-AVProMovieCapture#128]
**Describe the bug**
Unity editor crashes when stop recording

**Your Setup (please complete the following information):**
 - Unity version: 2020.1.7f
 - AVPro Movie Capture version: UnityPlugin-AVProMovieCapture-v4.6.5-Trial
 - Operating system version: macOS
 - Capture component used: CaptureFromTexture
 - Capture settings (resolution, frame-rate, codec): 1080x1920, 30fps, offline render, manual frame updates

**To Reproduce**
1) Created RenderTexture programmatically with 

```
renderTexture = new RenderTexture(1080, 1920, 24);
renderTexture.Create();
```

2) Start recording:

```
capture.SetSourceTexture(renderTexture);
capture.StartCapture();
```

3) Stop recording.

```
capture.StopCapture();
```

Actual behavior: Unity Editor crashed
Expected behavior: Video captured or error message received

**Logs**

```
[AVProMovieCapture] Stopping capture 50960
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
RenderHeads.Media.AVProMovieCapture.CaptureBase:StopCapture(Boolean, Boolean, Boolean) (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/CaptureBase.cs:2110)
ExportManager:EndExport() (at Assets/Scripts/ExportManager.cs:75)
ExportManager:Update() (at Assets/Scripts/ExportManager.cs:66)

(Filename: Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/CaptureBase.cs Line: 2110)

2021-09-28 18:37:11.768 Unity[12946:600257] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVAssetWriter endSessionAtSourceTime:] invalid parameter not satisfying: CMTIME_IS_NUMERIC(endTime)'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff38560b57 __exceptionPreprocess + 250
        1   libobjc.A.dylib                     0x00007fff713ec5bf objc_exception_throw + 48
        2   AVFoundation                        0x00007fff33da83e2 -[AVAssetWriter cancelWriting] + 0
        3   AVProMovieCapture                   0x000000014e94c5a7 EncodeMonoToAmbisonic + 13262
        4   AVProMovieCapture                   0x000000014e9485e5 Stop + 89
        5   ???                                 0x0000000170d6b686 0x0 + 6188086918
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Obtained 12 stack frames.
#0  0x007fff726dc33a in __pthread_kill
#1  0x007fff72663808 in abort
#2  0x007fff6f8c4458 in abort_message
#3  0x007fff6f8b58bf in demangling_unexpected_handler()
#4  0x007fff713ee5a9 in _objc_terminate()
#5  0x007fff6f8c3887 in std::__terminate(void (*)())
#6  0x007fff6f8c61a2 in __cxa_get_exception_ptr
#7  0x007fff6f8c6169 in __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
#8  0x007fff713ec6ed in objc_exception_throw
#9  0x007fff33da83e2 in -[AVAssetWriter cancelWriting]
#10 0x0000014e94c5a7 in EncodeMonoToAmbisonic
#11 0x0000014e9485e5 in Stop

```

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

**Comment by bakwc** [comment]
Seems like a duplicate of #125

**Comment by bakwc** [comment]
The problem was checked "Manual Update" box. Unchecked it and crashes stopped.

**Comment by MorrisRH** [comment]
The crash does appear to be the same as #125.

```Manual Update``` requires that the user passes in the data to be captured, failing to do so would result in an empty capture.

I'm going to close this issue as the crash is covered by #125 and the reported issue would appear to be user error ;)
