### ISSUE TITLE
Error: [AVProMovieCapture] Failed to create recorder

### ISSUE THREAD

**Issue by jhdot** [RenderHeads/UnityPlugin-AVProMovieCapture#332]
In editor works well but in iOS "Failed to create recorder" error happens.

 - Unity version: 2022.3.10f1
 - AVPro Movie Capture version: 5.1.8
 - Operating system version: iOS 16.6.1
 - Capture component used: Capture From Texture
 - Capture settings (resolution, frame-rate, codec): 1280x720, 30fps, H264 

**To Reproduce**
1. Set AVPro Movie Capture settings 
Photo Library Usage Description: This app requires access to the photo library to export movie.
Photo Library Add Usage Description: This app requires access to add exported movie into the Photo library.
2. Set Capture From Texture settings
- Manual Update: true
- Output/Folder: Photo Library
- Visual/Frame Update Mode: Automatic
- Audio Source: Unity
3. Call Functions
- SetSourceTxture()
- StartCapture()
Failed to create recorder

**Logs**
Error: [AVProMovieCapture] Failed to create recorder
RenderHeads.Media.AVProMovieCapture.CaptureBase:PrepareCapture()
RenderHeads.Media.AVProMovieCapture.CaptureBase:StartCapture()

**Screenshots**
![Image_20231017_155109_204](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/145401214/d749745e-7a40-4aac-8000-5cdaff861193)

PS) I tested with trial version and upgraded to 5.1.8 version by purchasing mobile version asset and clicking "Upgrade Now" button. But "Upgrade Now" button still exists. Is this normal?
![Screenshot 2023-10-17 at 4 33 01 PM](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/145401214/73c9059d-79d7-47d9-a9a2-dfb271b48958)

**Comment by jhdot** [comment]
I got the following error in the editor when I try to upgrade by importing purchased version.

Unable to update following assemblies:Assets/ExternalDependencyManager/Editor/Google.VersionHandler.dll (Name = Google.VersionHandler, Error = 131) (Output: /var/folders/pv/bm0gx_zj7_1cwb_0p7hry_t00000gn/T/tmp47e4ab7d.tmp)

Mono.CompilerServices.SymbolWriter.MonoSymbolFileException: Symbol file `Assets/ExternalDependencyManager/Editor/Google.VersionHandler.dll.mdb' does not match assembly
   at Mono.CompilerServices.SymbolWriter.MonoSymbolFile.ReadSymbolFile(String mdbFilename, Guid assemblyGuid)
   at Mono.Cecil.Mdb.MdbReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(Disposable`1 stream, String fileName, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at AssemblyUpdater.Core.AssemblyUpdaterContext.ReadAssembly(String assemblyPath, IAPIUpdaterListener listener, FileAccess mode, String[] searchPaths) in /Users/bokken/build/output/unity/unity/Editor/Tools/ScriptUpdater/AssemblyUpdater/Core/AssemblyUpdaterContext.cs:line 94
   at AssemblyUpdater.Core.AssemblyUpdaterContext.From(String assemblyPath, ConfigurationProvider configuration, String[] assemblySearchPaths, IAPIUpdaterListener listener) in /Users/bokken/build/output/unity/unity/Editor/Tools/ScriptUpdater/AssemblyUpdater/Core/AssemblyUpdaterContext.cs:line 34
   at AssemblyUpdater.Core.AssemblyUpdaterContext.From(String assemblyPath, String[] assemblySearchPaths, IAPIUpdaterListener listener) in /Users/bokken/build/output/unity/unity/Editor/Tools/ScriptUpdater/AssemblyUpdater/Core/AssemblyUpdaterContext.cs:line 25
   at AssemblyUpdater.Application.Program.<>c__DisplayClass0_0.<Main>b__1(UpdateOptions o) in /Users/bokken/build/output/unity/unity/Editor/Tools/ScriptUpdater/AssemblyUpdater/Application/Program.cs:line 62
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at AssemblyUpdater.Application.Program.Main(String[] args) in /Users/bokken/build/output/unity/unity/Editor/Tools/ScriptUpdater/AssemblyUpdater/Application/Program.cs:line 57
Assets/Plugins/Borodar/RainbowHierarchy/Assemblies/RainbowHierarchy.dll (Name = RainbowHierarchy, Error = 131) (Output: /var/folders/pv/bm0gx_zj7_1cwb_0p7hry_t00000gn/T/tmp289cf35c.tmp)

[AssemblyUpdater] Failed to resolve assembly Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a. SearchPaths: Assets/Plugins/Borodar/RainbowHierarchy/Assemblies, /Applications/Unity/Hub/Editor/2022.3.10f1/Unity.app/Contents/NetStandard/ref/2.1.0, /Applications/Unity/Hub/Editor/2022.3.10f1/Unity.app/Contents/NetStandard/compat/2.1.0/shims/netstandard, /Applications/Unity/Hub/Editor/2022.3.10f1/Unity.app/Contents/NetStandard/compat/2.1.0/shims/netfx, /Users/jaehoonchoi/work/olobo/Assets/Plugins, /Users/jaehoonchoi/work/olobo/Assets/ExternalDependencyManager/Editor, /Users/jaehoonchoi/work/olobo/Assets/ConsolePro/Editor, /Users/jaehoonchoi/work/olobo/Assets/Firebase/Plugins, /Users/jaehoonchoi/work/olobo/Assets/Firebase/Editor, /Users/jaehoonchoi/work/olobo/Assets/NuGet/Editor, /Users/jaehoonchoi/work/olobo/Assets/GifAssets/PowerGif, /Users/jaehoonchoi/work/olobo/Assets/AI Toolbox/Runtime, /Users/jaehoonchoi/work/olobo/Assets/AI Toolbox/Editor, /Users/jaehoonchoi/work/olobo/Assets/EasyColliderEditor/Scripts/Plugins, /Users/jaehoonchoi/work/olobo/Assets/Plugins/DiskUtils/x86, /Users/jaehoonchoi/work/olobo/Assets/Plugins/DiskUtils/x86_64, /Users/jaehoonchoi/work/olobo/Assets/Plugins/Demigiant/DOTweenPro, /Users/jaehoonchoi/work/olobo/Assets/Plugins/Demigiant/DOTween, /Users/jaehoonchoi/work/olobo/Assets/ExternalDependencyManager/Editor/1.2.176, /Users/jaehoonchoi/work/olobo/Assets/Firebase/Plugins/iOS, /Users/jaehoonchoi/work/olobo/Assets/Firebase/Plugins/x86_64, /Users/jaehoonchoi/work/olobo/Assets/SaveToMp3/Plugins/x86, /Users/jaehoonchoi/work/olobo/Assets/SaveToMp3/Plugins/x86_64, /Users/jaehoonchoi/work/olobo/Assets/Plugins/Crazy Minnow Studio/SALSA LipSync/Plugins, /Users/jaehoonchoi/work/olobo/Assets/Plugins/Crazy Minnow Studio/SALSA LipSync/Editor, /Users/jaehoonchoi/work/olobo/Assets/Plugins/Borodar/RainbowHierarchy/Assemblies, /Users/jaehoonchoi/work/olobo/Assets/Plugins/Dissonance/Plugins/x86, /Users/jaehoonchoi/work/olobo/Assets/Plugins/Dissonance/Plugins/x86_64, /Users/jaehoonchoi/work/olobo/Assets/Plugins/Demigiant/DOTweenPro/Editor, /Users/jaehoonchoi/work/olobo/Assets/Plugins/Demigiant/DemiLib/Core, /Users/jaehoonchoi/work/olobo/Assets/Plugins/Demigiant/DOTween/Editor, /Users/jaehoonchoi/work/olobo/Assets/Packages/Google.Apis.Core.1.57.0/lib/net45, /Users/jaehoonchoi/work/olobo/Assets/Packages/Google.Apis.Sheets.v4.1.57.0.2826/lib/net45, /Users/jaehoonchoi/work/olobo/Assets/Packages/Google.Apis.Auth.1.57.0/lib/net461, /Users/jaehoonchoi/work/olobo/Assets/Packages/Google.Apis.1.57.0/lib/net45, /Users/jaehoonchoi/work/olobo/Assets/AppCenter/Plugins/WSA/Core, /Users/jaehoonchoi/work/olobo/Assets/AppCenter/Plugins/WSA/IL2CPP, /Users/jaehoonchoi/work/olobo/Assets/AppCenter/Plugins/WSA/Analytics, /Users/jaehoonchoi/work/olobo/Assets/Plugins/Dissonance/Plugins/UWP/x86, /Users/jaehoonchoi/work/olobo/Assets/Plugins/Dissonance/Plugins/UWP/ARM, /Users/jaehoonchoi/work/olobo/Assets/Plugins/Dissonance/Plugins/UWP/ARM64, /Users/jaehoonchoi/work/olobo/Assets/Plugins/Dissonance/Plugins/UWP/x86_64, /Users/jaehoonchoi/work/olobo/Assets/Plugins/Demigiant/DemiLib/Core/Editor, /Users/jaehoonchoi/work/olobo/Assets/I2/Localization/Scripts/Editor/Unity XCode, /Users/jaehoonchoi/work/olobo/Assets/AppCenter/Plugins/WSA/IL2CPP/X64, /Users/jaehoonchoi/work/olobo/Assets/AppCenter/Plugins/WSA/IL2CPP/X86, /Users/jaehoonchoi/work/olobo/Assets/AppCenter/Plugins/WSA/IL2CPP/ARM, /Users/jaehoonchoi/work/olobo/Assets/AppCenter/Plugins/WSA/IL2CPP/ARM64, /Users/jaehoonchoi/work/olobo/Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Plugins/x86, /Users/jaehoonchoi/work/olobo/Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Plugins/x86_64, /Users/jaehoonchoi/work/olobo/Library/PackageCache/jillejr.newtonsoft.json-for-unity@13.0.102/Plugins/Newtonsoft.Json Editor, /Users/jaehoonchoi/work/olobo/Library/PackageCache/jillejr.newtonsoft.json-for-unity@13.0.102/Plugins/Newtonsoft.Json AOT, /Users/jaehoonchoi/work/olobo/Library/PackageCache/com.unity.ide.rider@3.0.26/Rider/Editor, /Users/jaehoonchoi/work/olobo/Library/PackageCache/com.unity.ext.nunit@1.0.6/net35/unity-custom, /Applications/Unity/Hub/Editor/2022.3.10f1/Unity.app/Contents/Managed, /Applications/Unity/Hub/Editor/2022.3.10f1/Unity.app/Contents/Managed/UnityEngine. Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Mono.Cecil.BaseAssemblyResolver.GetAssemblyInNetGac(AssemblyNameReference reference, ReaderParameters parameters)
   at Mono.Cecil.BaseAssemblyResolver.GetAssemblyInGac(AssemblyNameReference reference, ReaderParameters parameters)
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at APIUpdater.Framework.Core.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters) in /Users/bokken/build/output/unity/unity/Editor/Tools/ScriptUpdater/APIUpdater.Framework/Core/AssemblyResolver.cs:line 29
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Mono.Cecil.BaseAssemblyResolver.GetAssemblyInNetGac(AssemblyNameReference reference, ReaderParameters parameters)
   at Mono.Cecil.BaseAssemblyResolver.GetAssemblyInGac(AssemblyNameReference reference, ReaderParameters parameters)
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at APIUpdater.Framework.Core.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters) in /Users/bokken/build/output/unity/unity/Editor/Tools/ScriptUpdater/APIUpdater.Framework/Core/AssemblyResolver.cs:line 29
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.ModuleDefinition.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at AssemblyUpdater.Steps.MemberReferenceReplacer.ResolveIgnoringAssemblyResolutionFailures(TypeReference tbr) in /Users/bokken/build/output/unity/unity/Editor/Tools/ScriptUpdater/AssemblyUpdater/Steps/MemberReferenceReplacer.cs:line 281
   at AssemblyUpdater.Steps.MemberReferenceReplacer.MemberReferenceReplacementFor(MethodReference methodReference) in /Users/bokken/build/output/unity/unity/Editor/Tools/ScriptUpdater/AssemblyUpdater/Steps/MemberReferenceReplacer.cs:line 102
   at AssemblyUpdater.Steps.MemberReferenceReplacer.Visit(MethodReference methodReference, Context context) in /Users/bokken/build/output/unity/unity/Editor/Tools/ScriptUpdater/AssemblyUpdater/Steps/MemberReferenceReplacer.cs:line 46
   at Unity.Cecil.Visitor.Visitor.Visit(MethodBody methodBody, Context context) in /Users/bokken/build/output/unity/unity/Tools/BindingsGenerator/Unity.BindingsGenerator.Core/Unity.Cecil.Visitor/Visitor.cs:line 390
   at Unity.Cecil.Visitor.Visitor.Visit(MethodDefinition methodDefinition, Context context) in /Users/bokken/build/output/unity/unity/Tools/BindingsGenerator/Unity.BindingsGenerator.Core/Unity.Cecil.Visitor/Visitor.cs:line 303
   at Unity.Cecil.Visitor.Visitor.Visit(TypeDefinition typeDefinition, Context context) in /Users/bokken/build/output/unity/unity/Tools/BindingsGenerator/Unity.BindingsGenerator.Core/Unity.Cecil.Visitor/Visitor.cs:line 247
   at Unity.Cecil.Visitor.Visitor.Visit(ModuleDefinition moduleDefinition, Context context) in /Users/bokken/build/output/unity/unity/Tools/BindingsGenerator/Unity.BindingsGenerator.Core/Unity.Cecil.Visitor/Visitor.cs:line 223
   at Unity.Cecil.Visitor.Visitor.Visit(AssemblyDefinition assemblyDefinition, Context context) in /Users/bokken/build/output/unity/unity/Tools/BindingsGenerator/Unity.BindingsGenerator.Core/Unity.Cecil.Visitor/Visitor.cs:line 217
   at AssemblyUpdater.Steps.AssemblyUpdaterStepBase.Visit(AssemblyDefinition assemblyDefinition, Context context) in /Users/bokken/build/output/unity/unity/Editor/Tools/ScriptUpdater/AssemblyUpdater/Steps/AssemblyUpdaterStepBase.cs:line 21
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Unity.Cecil.Visitor.Visitor.Visit[T](T node, Context context) in /Users/bokken/build/output/unity/unity/Tools/BindingsGenerator/Unity.BindingsGenerator.Core/Unity.Cecil.Visitor/Visitor.cs:line 198
   at Unity.Cecil.Visitor.Extensions.DoAccept[T](T definition, Visitor visitor) in /Users/bokken/build/output/unity/unity/Tools/BindingsGenerator/Unity.BindingsGenerator.Core/Unity.Cecil.Visitor/Extensions.cs:line 57
   at Unity.Cecil.Visitor.Extensions.Accept(AssemblyDefinition assemblyDefinition, Visitor visitor) in /Users/bokken/build/output/unity/unity/Tools/BindingsGenerator/Unity.BindingsGenerator.Core/Unity.Cecil.Visitor/Extensions.cs:line 9
   at AssemblyUpdater.Steps.AssemblyUpdaterStepBase.Apply(AssemblyUpdaterContext context) in /Users/bokken/build/output/unity/unity/Editor/Tools/ScriptUpdater/AssemblyUpdater/Steps/AssemblyUpdaterStepBase.cs:line 16
   at AssemblyUpdater.Core.AssemblyUpdaterPipeline.RunUpdateRound(AssemblyUpdaterContext context) in /Users/bokken/build/output/unity/unity/Editor/Tools/ScriptUpdater/AssemblyUpdater/Core/AssemblyUpdaterPipeline.cs:line 42
   at AssemblyUpdater.Core.AssemblyUpdaterPipeline.Run(AssemblyUpdaterContext context) in /Users/bokken/build/output/unity/unity/Editor/Tools/ScriptUpdater/AssemblyUpdater/Core/AssemblyUpdaterPipeline.cs:line 29
   at AssemblyUpdater.Application.Program.UpdateAssembly(UpdateOptions config, AssemblyUpdaterContext context) in /Users/bokken/build/output/unity/unity/Editor/Tools/ScriptUpdater/AssemblyUpdater/Application/Program.cs:line 106
   at AssemblyUpdater.Application.Program.<>c__DisplayClass0_0.<Main>b__1(UpdateOptions o) in /Users/bokken/build/output/unity/unity/Editor/Tools/ScriptUpdater/AssemblyUpdater/Application/Program.cs:line 70
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at AssemblyUpdater.Application.Program.Main(String[] args) in /Users/bokken/build/output/unity/unity/Editor/Tools/ScriptUpdater/AssemblyUpdater/Application/Program.cs:line 57
Following assemblies were successfully updated but due to the failed ones above they were ignored (not copied to the destination folder):Assets/AI Toolbox/Editor/AiToolbox.Editor.dll	(Result = 0) (Output: /var/folders/pv/bm0gx_zj7_1cwb_0p7hry_t00000gn/T/tmp43a89b76.tmp)

**Comment by jhdot** [comment]
To compare mobile edition, I purchased Ultimate edition too. With Ultimate edition trial logo disappeared.  I think "Upgrade Now" button does not work well.

**Comment by Chris-RH** [comment]
With the mobile version, the editor version is still using the trial/watermark version, but will these will not be there when you run it on iOS/Android.

Can you reproduce this behaviour using a fresh project and just running the AVPro Movie Capture demo scenes?

**Comment by jhdot** [comment]
There occurs no error If I set Output/Folder to "Relative To Persistent Data".

**Comment by Chris-RH** [comment]
Did you follow all the steps here: https://www.renderheads.com/content/docs/AVProMovieCapture/articles/usage-photo-library.html

**Comment by jhdot** [comment]
I missed inserting request authorisation scrpt. I'll test with the script. Thank you for fast help.

**Comment by jhdot** [comment]
It works well. Thank you so much.

**Comment by Chris-RH** [comment]
Great news :) You are most welcome :)
